blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_home, name='blog_home'),
    path('<int:post_id>/', views.blog_detail, name='blog_detail'),
    path('post/', views.blog_post, name='blog_post'),
]

course/urls.py
from django.urls import path
from .views import CourseDeleteView, CourseAllView, CourseListView, CourseDetailView, CourseCreateView, CourseUpdateView

app_name = 'course'

urlpatterns = [
    path('', CourseAllView.as_view(), name='course_home'),
    path('list/', CourseListView.as_view(), name='course_list'),
    path('create/', CourseCreateView.as_view(), name='course_create'),
    path('detail/<int:pk>/', CourseDetailView.as_view(), name='course_detail'),
    path('delete/<int:pk>/', CourseDeleteView.as_view(), name='course_delete'),
    path('update/<int:pk>/', CourseUpdateView.as_view(), name='course_update'),
]

django_examine/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('blog.urls', namespace='root')),
    path('account/', include('account.urls', namespace='account')),
    path('course/', include('course.urls', namespace='course')),
    path('mdeditor/', include('mdeditor.urls')),
    url('', include('social_django.urls', namespace='social'))
]

# 为每个多媒体文件添加对应的urlpatterns的列表里元素
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from mdeditor.fields import MDTextField

def user_directory_path(instance, filename):
    return 'course/user_{0}/{1}'.format(instance.user.username, filename)


class Course(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='courses_user')
    title = models.CharField(max_length=128)
    intro = models.TextField()
    content = MDTextField(blank=True)
    create_time = models.DateTimeField(default=timezone.now)
    video = models.FileField(blank=True, upload_to=user_directory_path)
    attach = models.FileField(blank=True, upload_to=user_directory_path)

    class Meta:
        ordering = ('-create_time',)

    def __str__(self):
        return self.title

course/forms.py
from django import forms
from .models import Course
from mdeditor.fields import MDTextFormField


class CourseCreateForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ('title', 'intro', 'content', 'video', 'attach',)

course/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from .models import Course
from .forms import CourseCreateForm
from braces.views import LoginRequiredMixin
from django.urls import reverse_lazy
from django.http import JsonResponse


class CourseAllView(ListView):
    model = Course
    template_name = 'course/home.html'
    context_object_name = 'courses'


class UserMixin:  # 筛选用户的类
    def get_queryset(self):
        qs = super(UserMixin, self).get_queryset()
        return qs.filter(user=self.request.user)


class UserCourseMixin(UserMixin, LoginRequiredMixin):
    model = Course
    login_url = '/account/login/'


class CourseListView(UserCourseMixin, ListView):
    template_name = 'course/course_list.html'
    context_object_name = 'courses'


class CourseUpdateView(UserCourseMixin, UpdateView):
    fields = ['title', 'intro', 'content', 'video', 'attach']
    template_name = 'course/course_edit.html'
    success_url = '/course/list/'


class CourseCreateView(UserCourseMixin, CreateView):
    fields = ['title', 'intro', 'content', 'video', 'attach']
    template_name = 'course/course_create.html'

    def post(self, request, *args, **kwargs):
        form = CourseCreateForm(request.POST, request.FILES)
        if form.is_valid():
            new_course = form.save(commit=False)
            new_course.user = self.request.user
            new_course.save()
            return redirect('course:course_list')
        return self.render_to_response({'form': form})


class CourseDetailView(UserCourseMixin, DetailView):
    template_name = 'course/course_detail.html'


class CourseDeleteView(UserCourseMixin, DeleteView):
    success_url = reverse_lazy('course:course_list')

    def dispatch(self, *args, **kwargs):
        r = DeleteView.dispatch(self, *args, **kwargs)
        if self.request.is_ajax():
            return JsonResponse({'result': 'OK'})
        else:
            return r

templates/course/course_create.html
{% extends 'base.html' %}

{% block title %}
    创建课程
{% endblock %}

{% block header %}
    {% include 'course_header.html' %}
{% endblock %}

{% block content %}
    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <form action="." method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {# {{ form.as_p }} #}
                    <div class="row" style="margin-top: 10px;">
                        <div class="col-md-3">课程标题：</div>
                        <div class="col-md-9">{{ form.title }}</div>
                    </div>
                    <div class="row" style="margin-top: 10px;">
                        <div class="col-md-3">课程介绍：</div>
                        <div class="col-md-9">{{ form.intro }}</div>
                    </div>
                    <div class="row" style="margin-top: 10px;">
                        <div class="col-md-3">上传视频：</div>
                        <div class="col-md-9">{{ form.video }}</div>
                    </div>
                    <div class="row" style="margin-top: 10px;">
                        <div class="col-md-3">上传附件：</div>
                        <div class="col-md-9">{{ form.attach }}</div>
                    </div>
                    <input class="btn btn-primary float-right" type="submit" value="发布课程">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/course/course_detail.html
{% extends 'base.html' %}

{% block title %}
    课程详情
{% endblock %}

{% block header %}
    {% include 'course_header.html' %}
{% endblock %}

{% block content %}
    <!-- Main Content -->
    <div class="container">
        <div class="row text-center">
            <div class="col-lg-8 col-md-10 mx-auto">
                <h1>{{ object.title }}</h1>
                <p>讲师：{{ object.user.username }}</p>
                <p>简介：{{ object.intro }}</p>
                <p>简介：{{ object.content }}</p>
                {% if object.video %}
                    <video src="{{ object.video.url }}" controls="controls" width="800"></video>
                {% else %}
                    <p>没有视频内容</p>
                {% endif %}
                {% if object.attach %}
                    <p>下载课件：<a href="{{ object.attach.url }}">{{ object.attach.name | slice:"15:" }}</a></p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/course/course_edit.html
{% extends 'base.html' %}

{% block title %}
    修改课程
{% endblock %}

{% block header %}
    {% include 'course_header.html' %}
{% endblock %}

{% block content %}
    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-10 col-md-11 mx-auto">
                <form action="." method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.media }}
                    {{ form.as_p }}
                    {#                    <div class="row" style="margin-top: 10px;">#}
                    {#                        <div class="col-md-3">课程标题：</div>#}
                    {#                        <div class="col-md-9">{{ form.title }}</div>#}
                    {#                    </div>#}
                    {#                    <div class="row" style="margin-top: 10px;">#}
                    {#                        <div class="col-md-3">课程介绍：</div>#}
                    {#                        <div class="col-md-9">{{ form.intro }}</div>#}
                    {#                    </div>#}
                    {#                    <div class="row" style="margin-top: 10px;">#}
                    {#                        <div class="col-md-3">课程内容：</div>#}
                    {#                        <div class="col-md-9">{{ form.content }}</div>#}
                    {#                    </div>#}
                    {#                    <div class="row" style="margin-top: 10px;">#}
                    {#                        <div class="col-md-3">上传视频：</div>#}
                    {#                        <div class="col-md-9">{{ form.video }}</div>#}
                    {#                    </div>#}
                    {#                    <div class="row" style="margin-top: 10px;">#}
                    {#                        <div class="col-md-3">上传附件：</div>#}
                    {#                        <div class="col-md-9">{{ form.attach }}</div>#}
                    {#                    </div>#}
                    <input class="btn btn-primary float-right" type="submit" value="发布课程">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/course/course_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    课程列表
{% endblock %}

{% block header %}
    {% include 'course_header.html' %}
{% endblock %}

{% block content %}
    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-9 col-md-11 mx-auto">
                <table class="table table-responsive table-hover">
                    <tr>
                        <td>序号</td>
                        <td>标题</td>
                        <td>讲师</td>
                        <td>日期</td>
                        <td>操作</td>
                    </tr>
                    {% for course in courses %}
                        <tr id="course_{{ course.id }}">
                            <td>{{ forloop.counter }}</td>
                            <td>{{ course.title }}</td>
                            <td>{{ course.user.username }}</td>
                            <td>{{ course.create_time }}</td>
                            <td><a class="detail" target="_blank" href="{% url 'course:course_detail' course.id %}">
                                <i class="fa fa-search" aria-hidden="true"></i></a>
                                <a style="margin-left: 20px;" class="delete"
                                   href="{% url 'course:course_delete' course.id %}">
                                    <i class="fa fa-trash" aria-hidden="true"></i></a>
                                <a style="margin-left: 20px;" class="update"
                                   href="{% url 'course:course_update' course.id %}">
                                    <i class="fa fa-wrench" aria-hidden="true"></i></a>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
                <div class="text-right">
                    <a href="{% url 'course:course_create' %}">
                        <button type="button" class="btn btn-primary">发布课程</button>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            var onDelete = function () {
                alert("Delete it?")

                $.ajaxSetup({
                    data: {csrfmiddlewaretoken: '{{ csrf_token }}'},
                });

                $.post(this.href, function (data) {
                    if (data.result == "OK") {
                        window.location.reload()
                    } else {
                        alert("something is wrong.")
                    }
                }).fail(function () {
                    alert("error")
                })
                return false
            }

            $(".delete").click(onDelete)
        })
    </script>
{% endblock %}

templates/course/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    所有课程
{% endblock %}

{% block header %}
    {% include 'course_header.html' %}
{% endblock %}

{% block content %}
    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <table class="table table-hover">
                    <tr>
                        <td>序号</td>
                        <td>标题</td>
                        <td>讲师</td>
                        <td>日期</td>
                    </tr>
                    {% for course in courses %}
                        <tr id="course_{{ course.id }}">
                            <td>{{ forloop.counter }}</td>
                            <td><a class="details" target="_blank"
                                   href="{% url 'course:course_detail' course.id %}">{{ course.title }}</a></td>
                            <td>{{ course.user.username }}</td>
                            <td>{{ course.create_time }}</td>
                        </tr>
                    {% endfor %}
                </table>
                <div class="text-right">
                    <a href="{% url 'course:course_create' %}">
                        <button type="button" class="btn btn-primary">发布课程</button>
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}