blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_home, name='blog_home'),
    path('<int:post_id>/', views.blog_detail, name='blog_detail'),
    path('post/', views.blog_post, name='blog_post'),
]

django_examine/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('blog.urls', namespace='root')),
    path('account/', include('account.urls', namespace='account')),
    path('course/', include('course.urls', namespace='course')),
    path('mdeditor/', include('mdeditor.urls')),
    url('', include('social_django.urls', namespace='social'))
]

# 为每个多媒体文件添加对应的urlpatterns的列表里元素
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Posts(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_post')
    content = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    is_recommend = models.BooleanField(default=False)

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from .models import Posts


class PostsForm(forms.ModelForm):
    class Meta:
        model = Posts
        fields = ('title', 'content',)

blog/views.py
from django.shortcuts import render
from .models import Posts
from django.contrib.auth.decorators import login_required
from .forms import PostsForm
from django.http import HttpResponseRedirect, JsonResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def blog_home(request):
    posts = Posts.objects.all()
    paginator = Paginator(posts, 5)
    page = request.GET.get('page')
    try:
        current_page = paginator.page(page)
    except PageNotAnInteger:
        current_page = paginator.page(1)
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)
    current_posts = current_page.object_list
    return render(request, 'blog/home.html', {'posts': current_posts, 'page': current_page})


def blog_detail(request, post_id):
    post = Posts.objects.get(id=post_id)
    return render(request, 'blog/detail.html', {'post': post})


@login_required
def blog_post(request):
    if request.method == "GET":
        form = PostsForm()
        return render(request, 'blog/post.html', {'form': form})
    if request.method == "POST":
        form = PostsForm(request.POST)
        if form.is_valid():
            try:
                post = form.save(commit=False)
                post.author = request.user
                post.save()
            except Exception as e:
                print(str(e))
                return JsonResponse({'result': str(e)})
            else:
                return JsonResponse({'result': 'success'})
        else:
            return JsonResponse({'result': 'invalid'})

templates/blog/detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    宁静致远 - {{ post.title }}
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.css' %}">
{% endblock %}

{% block header %}
    <!-- Page Header -->
    <header class="masthead" style="background-image: url('{% static 'img/post-bg.jpg' %}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="post-heading">
                        <h1 class="text-center">{{ post.title }}</h1>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

{% block content %}
    <!-- Post Content -->
    <article>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <p class="text-center">
                        <span>作者：{{ post.author.username }}</span>
                        <span style="margin-left: 10px">发布时间：{{ post.publish }}</span>
                    </p>
                    {# <div>{{ post.content }}</div> #}
                    <div id="editormd-view">
                                            <textarea id="append-test" style="display: none;">
{{ post.content }}
                                            </textarea>
                    </div>
                </div>
            </div>
        </div>
    </article>
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'editor/lib/marked.min.js' %}"></script>
    <script src="{% static 'editor/lib/prettify.min.js' %}"></script>
    <script src="{% static 'editor/lib/raphael.min.js' %}"></script>
    <script src="{% static 'editor/lib/underscore.min.js' %}"></script>
    <script src="{% static 'editor/lib/sequence-diagram.min.js' %}"></script>
    <script src="{% static 'editor/lib/flowchart.min.js' %}"></script>
    <script src="{% static 'editor/lib/jquery.flowchart.min.js' %}"></script>
    <script src="{% static 'editor/editormd.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            editormd.markdownToHTML("editormd-view", {
                htmlDecode: "style, script, iframe",
                emoji: true,
                taskList: true,
                tex: true,
                flowChart: true,
                sequenceDiagram: true,
            })
        })
    </script>
{% endblock %}

templates/blog/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    博客文章
{% endblock %}

{% block header %}
    <!-- Page Header -->
    <header class="masthead" style="background-image: url('{% static 'img/home-bg.jpg' %}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>宁静致远</h1>
                        <span class="subheading">一个由Bootstrap和Django创建的博客</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

{% block content %}
    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                {% for post in posts %}
                    <div class="post-preview">
                        <a href="{{ post.id }}"><h2 class="post-title">{{ post.title }}</h2></a>
                        <p style="font: caption;" class="post-meta">作者：<a
                                href="#">{{ post.author }}</a>　{{ post.publish }}</p>
                    </div>
                    <hr>
                {% endfor %}
                <!-- Pager -->
                <div class="clearfix">
                    {% include 'paginator.html' %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/blog/post.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block header %}
    {% include 'backend_header.html' %}
{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'editor/css/editormd.min.css' %}">
{% endblock %}

{% block content %}
    <!-- Main Content -->
    <div class="container">
        <div class="row text-center">
            <div class="col-lg-9 col-md-11 mx-auto">
                <form class="form-horizontal" action="" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="">标题：</div>
                        <div class="col-sm-10">{{ form.title }}</div>
                    </div>
                    <div class="row">
                        <div class="">内容：</div>
                        {# <div class="col-sm-10">{{ form.content }}</div> #}
                        <div id="md-editor" class="">
                            <textarea style="display: none;" id="id_content"></textarea>
                        </div>
                    </div>
                    <input type="button" onclick="post_blog()" class="btn btn-primary" value="发布文章">
                </form>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
    <script type="text/javascript" src="{% static 'editor/editormd.min.js' %}"></script>
    <script type="text/javascript">
        function post_blog() {
            var title = $("#id_title").val();
            var content = $("#id_content").val();
            console.log(title, content)

            $.ajaxSetup({
                data: {csrfmiddlewaretoken: "{{ csrf_token }}"},
            })

            $.ajax({
                type: "POST",
                url: "{% url 'blog:blog_post' %}",
                data: {
                    "title": title,
                    "content": content,
                },
                success: function (e) {
                    if (e.result == "success") {
                        layer.msg("文章发布成功")
                        location.href = "{% url 'blog:blog_home' %}"
                    } else if (e.result == "invalid") {
                        layer.msg("验证不通过")
                    } else {
                        layer.msg(e.result)
                    }
                }
            })
        }

        // 加载md编辑器的js代码
        $(function () {
            editor = editormd("md-editor", {
                width: "100%",
                height: 840,
                syncScrolling: "single",
                path: "{% static 'editor/lib/' %}"
            })

        })
    </script>
{% endblock %}