account/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html'), name='user_login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='account/logout.html'), name='user_logout'),
    path('register/', views.register, name='user_register'),
    # 修改密码
    path('password-change/', auth_views.PasswordChangeView.as_view(template_name='account/password_change_form.html',
                                                                   success_url='/account/password-change-done/'),
         name='password_change'),
    path('password-change-done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='account/password_change_done.html'),
         name='password_change_done'),
    # 重置密码
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='account/password_reset_form.html',
                                                                 email_template_name='account/password_reset_email.html',
                                                                 subject_template_name='account/password_reset_subject.txt',
                                                                 success_url='/account/password-reset-done/'),
         name='password_reset'),
    path('password-reset-done/',
         auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html',
                                                     success_url='/account/password-reset-complete/'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'),
         name='password_reset_complete'),
    # 个人信息修改
    path('myself/', views.myself, name='myself'),
    path('myself-edit/', views.myself_edit, name='myself_edit'),
    path('my-image/', views.my_image, name='my_image'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_home, name='blog_home'),
    path('<int:post_id>/', views.blog_detail, name='blog_detail'),
    path('post/', views.blog_post, name='blog_post'),
]

course/urls.py
from django.urls import path
from .views import CourseDeleteView, CourseAllView, CourseListView, CourseDetailView, CourseCreateView, CourseUpdateView

app_name = 'course'

urlpatterns = [
    path('', CourseAllView.as_view(), name='course_home'),
    path('list/', CourseListView.as_view(), name='course_list'),
    path('create/', CourseCreateView.as_view(), name='course_create'),
    path('detail/<int:pk>/', CourseDetailView.as_view(), name='course_detail'),
    path('delete/<int:pk>/', CourseDeleteView.as_view(), name='course_delete'),
    path('update/<int:pk>/', CourseUpdateView.as_view(), name='course_update'),
]

django_examine/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('blog.urls', namespace='root')),
    path('account/', include('account.urls', namespace='account')),
    path('course/', include('course.urls', namespace='course')),
    path('mdeditor/', include('mdeditor.urls')),
    url('', include('social_django.urls', namespace='social'))
]

# 为每个多媒体文件添加对应的urlpatterns的列表里元素
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/backend_header.html
{% load staticfiles %}
<!-- Page Header -->
<header class="masthead" style="background-image: url('{% static 'img/backend-bg.jpg' %}')">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h1>宁静致远</h1>
                    <span class="subheading">一个由Bootstrap和Django创建的博客</span>
                </div>
            </div>
        </div>
    </div>
</header>

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %}{% endblock %}</title>
    <style type="text/css">
        #dropdownMenuButton {
            padding: 7px 10px;
        }
    </style>
    {% block style %}{% endblock %}

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom fonts for this template -->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.loli.net/css?family=Lora:400,700,400italic,700italic' rel='stylesheet'
          type='text/css'>
    <link href='https://fonts.loli.net/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
          rel='stylesheet' type='text/css'>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">
</head>
<body>
{% include 'navigation.html' %}
{% block header %}{% endblock %}
{% block content %}{% endblock %}
<hr>
{% include 'footer.html' %}
{% block script %}
    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Custom scripts for this template -->
    <script src="{% static 'js/clean-blog.min.js' %}"></script>
{% endblock %}
</body>
</html>

templates/course_header.html
{% load staticfiles %}
<!-- Page Header -->
<header class="masthead" style="background-image: url('{% static 'img/course-bg.jpg' %}')">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h1>宁静致远</h1>
                    <span class="subheading">一个由Bootstrap和Django创建的博客</span>
                </div>
            </div>
        </div>
    </div>
</header>

templates/footer.html
<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="https://articuly.com" target="_blank">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-wordpress fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://weibo.com/articuly" target="_blank">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-weibo fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-weixin fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://github.com/articuly" target="_blank">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                </ul>
                <p class="copyright text-muted">Copyright &copy; Articuly.com 2020</p>
            </div>
        </div>
    </div>
</footer>

templates/navigation.html
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="{% url 'blog:blog_home' %}">宁静致远</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation">菜单<i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item"><a class="nav-link" href="{% url 'blog:blog_home' %}">主页</a></li>
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'course:course_list' %}">课程列表</a></li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'course:course_home' %}">所有课程</a></li>
                {% endif %}
                {% if user.is_authenticated %}
                    <li class="nav-item d-lg-none"><a class="nav-link" href="{% url 'blog:blog_post' %}">发表文章</a></li>
                    <li class="nav-item d-lg-none"><a class="nav-link" href="{% url 'course:course_create' %}">发布课程</a>
                    </li>
                    <li class="nav-item d-lg-none"><a class="nav-link" href="{% url 'account:myself' %}">个人信息</a></li>
                    <li class="nav-item d-lg-none"><a class="nav-link"
                                                      href="{% url 'account:password_change' %}">修改密码</a></li>
                    <li class="nav-item d-lg-none"><a class="nav-link" href="{% url 'account:user_logout' %}">退出</a>
                    </li>
                    <div class="dropdown d-none d-lg-block">
                        <button class="btn btn-outline-light dropdown-toggle" type="button" id="dropdownMenuButton"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            您好，{{ user.username }}
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="{% url 'blog:blog_post' %}">发表文章</a>
                            <a class="dropdown-item" href="{% url 'course:course_create' %}">发布课程</a>
                            <a class="dropdown-item" href="{% url 'account:myself' %}">个人信息</a>
                            <a class="dropdown-item" href="{% url 'account:password_change' %}">修改密码</a>
                            <a class="dropdown-item" href="{% url 'account:user_logout' %}">退出</a>
                        </div>
                    </div>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'account:user_login' %}">登陆</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'account:user_register' %}">注册</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/paginator.html
<div class="clearfix">
    <span class="step-link">
        {% if page.has_next %}
            <a class="btn btn-primary float-right" href="?page={{ page.next_page_number }}">下一页</a>
        {% endif %}
        <span class="current btn btn-primary float-right">第{{ page.number }}页/共{{ page.paginator.num_pages }}页</span>
        {% if page.has_previous %}
            <a class="btn btn-primary float-right" href="?page={{ page.previous_page_number }}">上一页</a>
        {% endif %}
    </span>
</div>